data_loc: /Users/koustuvs/mlp/cluttr_data
seed: 42
world_id: 0
template_type: amt # synthetic or amt
template_folder: clutrr/templates # template folder which should have three files, train.json, valid.json, test.json. In case of synthetic, only train.json is required
gender_map: clutrr/store/relations_store.yaml
names_url: https://github.com/PhantomInsights/baby-names-analysis/raw/master/data/data.csv
names_file: clutrr/names.csv
num_names: 1000 # number of names to consider for male and female names
num_train: 500
num_valid: 50
num_test: 50
